/**
 * Domain taxonomy for the saree catalog.
 * Maharashtrian collections are treated as first-class, priority categories;
 * other Indian regional collections are supported as a secondary tier.
 * These are used to seed the database and to drive frontend/admin filter UIs.
 */

export const CATEGORY_GROUPS = {
  MAHARASHTRIAN: "maharashtrian",
  PAN_INDIAN: "pan_indian",
} as const;

export type CategoryGroup = (typeof CATEGORY_GROUPS)[keyof typeof CATEGORY_GROUPS];

/** Priority Maharashtrian saree categories (top-level + sub-categories under Paithani/Nauvari). */
export const MAHARASHTRIAN_CATEGORIES = [
  {
    slug: "paithani",
    name: "Paithani Sarees",
    description: "Traditional hand-woven Paithani sarees",
    children: [
      "Yeola Paithani",
      "Pure Silk Paithani",
      "Handloom Paithani",
      "Semi Paithani",
      "Tissue Paithani",
      "Muniya Border Paithani",
      "Bangdi Mor Paithani",
      "Lotus Paithani",
      "Peacock Design Paithani",
      "Ajanta Lotus Paithani",
      "Asawali Paithani",
      "Narali Border Paithani",
      "Kalamkari Paithani",
    ],
  },
  {
    slug: "nauvari",
    name: "Nauvari Sarees (9 Yards)",
    description: "Traditional nine-yard Maharashtrian sarees",
    children: [
      "Kashta Sarees",
      "Traditional Maharashtrian Nauvari",
      "Cotton Nauvari",
      "Silk Nauvari",
      "Ready-to-Wear Nauvari",
    ],
  },
  { slug: "peshwai", name: "Peshwai Sarees", description: "Peshwai era inspired sarees", children: [] },
  { slug: "narayan-peth", name: "Narayan Peth Sarees", description: "Narayan Peth handloom sarees", children: [] },
  { slug: "solapuri-cotton", name: "Solapuri Cotton Sarees", description: "Solapur cotton weaves", children: [] },
  { slug: "ilkal", name: "Ilkal Sarees", description: "Traditional Ilkal weave", children: [] },
  { slug: "khun-fabric", name: "Khun Fabric Sarees", description: "Khun fabric blouse & saree pieces", children: [] },
  {
    slug: "maharashtrian-bridal",
    name: "Maharashtrian Bridal Sarees",
    description: "Bridal collection for Maharashtrian weddings",
    children: [],
  },
  {
    slug: "maharashtrian-wedding",
    name: "Maharashtrian Wedding Collection",
    description: "Wedding function sarees",
    children: [],
  },
  {
    slug: "maharashtrian-festive",
    name: "Maharashtrian Festive Collection",
    description: "Festival wear sarees",
    children: [],
  },
  { slug: "maharashtrian-haldi", name: "Maharashtrian Haldi Collection", description: "Haldi ceremony sarees", children: [] },
  {
    slug: "maharashtrian-reception",
    name: "Maharashtrian Reception Collection",
    description: "Reception sarees",
    children: [],
  },
  {
    slug: "maharashtrian-traditional",
    name: "Maharashtrian Traditional Wear",
    description: "Everyday traditional wear",
    children: [],
  },
] as const;

/** Secondary pan-Indian saree categories. */
export const PAN_INDIAN_CATEGORIES = [
  "Banarasi Silk",
  "Kanjivaram Silk",
  "Patola",
  "Bandhani",
  "Chanderi",
  "Maheshwari",
  "Kota Doria",
  "Tussar Silk",
  "Organza",
  "Linen",
  "Cotton",
  "Georgette",
  "Chiffon",
  "Crepe",
  "Satin Silk",
  "Soft Silk",
  "Tissue Silk",
  "Handloom Collection",
  "Printed Sarees",
  "Embroidered Sarees",
  "Party Wear Sarees",
  "Office Wear Sarees",
  "Casual Wear Sarees",
  "Designer Sarees",
  "Wedding Collection",
  "Festive Collection",
  "Luxury Collection",
] as const;

export const FABRICS = [
  "Pure Silk",
  "Semi Silk",
  "Cotton",
  "Cotton Silk",
  "Linen",
  "Organza",
  "Chiffon",
  "Georgette",
  "Tissue",
  "Tussar Silk",
  "Banarasi Silk",
  "Kanjivaram Silk",
  "Khun Fabric",
  "Modal Silk",
  "Crepe",
  "Satin",
  "Art Silk",
] as const;

export const OCCASIONS = [
  "Maharashtrian Wedding",
  "Bride",
  "Bride's Mother",
  "Haldi Ceremony",
  "Mehendi Ceremony",
  "Sangeet",
  "Reception",
  "Engagement",
  "Gudi Padwa",
  "Ganesh Festival",
  "Diwali",
  "Navratri",
  "Mangalagaur",
  "Vat Pournima",
  "Traditional Functions",
  "Office Wear",
  "Daily Wear",
  "Party Wear",
  "Temple Visit",
  "Housewarming",
  "Baby Shower",
  "Naming Ceremony",
] as const;

export const BORDER_TYPES = [
  "Muniya Border",
  "Bangdi Mor Border",
  "Narali Border",
  "Peacock Border",
  "Lotus Border",
  "Temple Border",
  "Zari Border",
  "Antique Gold Border",
  "Silver Border",
  "Meenakari Border",
  "Contrast Border",
  "Plain Border",
  "Traditional Border",
] as const;

export const PALLU_DESIGNS = [
  "Peacock Pallu",
  "Lotus Pallu",
  "Asawali Pallu",
  "Floral Pallu",
  "Paisley Pallu",
  "Traditional Maharashtrian Pallu",
  "Temple Design",
  "Muniya Design",
  "Handwoven Pallu",
  "Rich Zari Pallu",
] as const;

export const DESIGN_PATTERNS = [
  "Peacock",
  "Lotus",
  "Paisley",
  "Mango",
  "Floral",
  "Leaf",
  "Temple",
  "Ajanta Motifs",
  "Elephant",
  "Parrot",
  "Muniya",
  "Bangdi Mor",
  "Asawali",
  "Kalamkari",
  "Butti",
  "Checks",
  "Stripes",
  "Jacquard",
  "Embroidery",
  "Digital Print",
  "Hand Block Print",
  "Handwoven",
  "Zari Work",
  "Resham Work",
  "Stone Work",
  "Mirror Work",
  "Thread Work",
] as const;

export const COLORS = [
  "Purple",
  "Magenta",
  "Royal Blue",
  "Peacock Blue",
  "Bottle Green",
  "Parrot Green",
  "Mustard Yellow",
  "Kesari (Saffron)",
  "Red",
  "Maroon",
  "Wine",
  "Pink",
  "Rani Pink",
  "Orange",
  "Emerald Green",
  "Turquoise",
  "Black",
  "White",
  "Cream",
  "Beige",
  "Golden",
  "Silver",
] as const;

export const WEAVING_TECHNIQUES = [
  "Handloom",
  "Machine Made",
  "Power Loom",
  "Zari Weaving",
  "Tie & Dye",
  "Block Print",
  "Digital Print",
  "Kalamkari",
] as const;

/** SEO landing pages seeded at launch, keyed by slug. */
export const SEO_LANDING_PAGES = [
  { slug: "buy-paithani-sarees-online", title: "Buy Paithani Sarees Online" },
  { slug: "pure-silk-paithani", title: "Pure Silk Paithani" },
  { slug: "yeola-paithani-collection", title: "Yeola Paithani Collection" },
  { slug: "maharashtrian-wedding-sarees", title: "Maharashtrian Wedding Sarees" },
  { slug: "nauvari-sarees-online", title: "Nauvari Sarees Online" },
  { slug: "ready-to-wear-nauvari", title: "Ready-to-Wear Nauvari" },
  { slug: "maharashtrian-bridal-collection", title: "Maharashtrian Bridal Collection" },
  { slug: "gudi-padwa-sarees", title: "Gudi Padwa Sarees" },
  { slug: "diwali-sarees", title: "Diwali Sarees" },
  { slug: "ganesh-festival-sarees", title: "Ganesh Festival Sarees" },
  { slug: "narayan-peth-sarees", title: "Narayan Peth Sarees" },
  { slug: "solapuri-cotton-sarees", title: "Solapuri Cotton Sarees" },
  { slug: "traditional-maharashtrian-sarees", title: "Traditional Maharashtrian Sarees" },
  { slug: "best-saree-shop-in-maharashtra", title: "Best Saree Shop in Maharashtra" },
  { slug: "premium-paithani-collection", title: "Premium Paithani Collection" },
  { slug: "handloom-maharashtra-sarees", title: "Handloom Maharashtra Sarees" },
] as const;
