export const FABRIC_OPTIONS = [
  "Pure Silk",
  "Semi Silk",
  "Cotton",
  "Cotton Silk",
  "Linen",
  "Organza",
  "Chiffon",
  "Georgette",
  "Tissue",
  "Tussar Silk",
  "Banarasi Silk",
  "Kanjivaram Silk",
  "Khun Fabric",
  "Modal Silk",
  "Crepe",
  "Satin",
  "Art Silk",
] as const;

/** Standard wash-care guidance per fabric, auto-filled when a fabric is picked (editable after). */
export const WASH_CARE_BY_FABRIC: Record<string, string> = {
  "Pure Silk": "Dry clean only. Avoid direct sunlight and store in a cotton cloth bag.",
  "Semi Silk": "Dry clean recommended. Hand wash separately in cold water if needed, do not wring.",
  Cotton: "Machine or hand wash in cold water with mild detergent. Iron on medium heat while slightly damp.",
  "Cotton Silk": "Hand wash in cold water separately, or dry clean. Do not bleach. Iron on low heat.",
  Linen: "Machine wash cold on a gentle cycle or hand wash. Iron while damp on medium-high heat.",
  Organza: "Dry clean only. Store flat or on a padded hanger to avoid creasing.",
  Chiffon: "Hand wash in cold water with mild detergent. Do not wring; drip dry in shade.",
  Georgette: "Hand wash cold or dry clean. Iron on low heat on the reverse side.",
  Tissue: "Dry clean only. Handle with care to avoid snags on the zari work.",
  "Tussar Silk": "Dry clean only. Avoid folding along the same lines repeatedly to prevent fabric wear.",
  "Banarasi Silk": "Dry clean only. Store wrapped in muslin cloth, away from direct light.",
  "Kanjivaram Silk": "Dry clean only. Store flat, refold periodically to avoid permanent creases.",
  "Khun Fabric": "Hand wash in cold water separately. Dry in shade to preserve color.",
  "Modal Silk": "Hand wash in cold water or dry clean. Do not bleach. Iron on low heat.",
  Crepe: "Dry clean recommended, or hand wash cold. Do not wring; hang dry in shade.",
  Satin: "Dry clean only. Iron on low heat on the reverse side if needed.",
  "Art Silk": "Hand wash in cold water separately. Do not bleach or wring. Dry in shade.",
};
